language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: DSvHlQcVI3axwVMbSES5uieFpNqTnkdYF9BnSlzI+zTTgm6xkI53nZpVKrpMQiAsMP+NikUdc17SVI8rYPZnSh1EwOGI3SFNLgGkv7gh1lkB5PbiVgvXki7qxEYLj6nkTikypcWqWKiLMLUmUzjEuceX5QCyP+cdUnmq+3hqYTvbftVcK4O4ajJdTOKMq1fJRfwNCqLSsfDynZqpCiH1p7Jel0umO61drljAlxb6mNqmfYCaBEXRC9BoGm4SH/IKbFUSWjFQoZMpDtqnOniHqCXjxlwBCUFKEdSFmE4ilwPaknIT8kxhpsoFcqVdmQLW2sF1Kl6TiUf8ouECiVANgHmuEg7zF2DPNXmM2sorQI5qXQF6hj/VB8ALhYNOmsIqMlcgIZyo5Y5CQi5+COl1Pa+7WE5wDNK1JB/OQuiqHjWOsl2LlafIepI2pSaDfAN9UrPQ/M685H8uC8a+NJWwjt27+0fNi0b0dt0ZZ+Zz+zK0Ife3hvkfRjBlxzecLBdibG7+pzdFKEtcEVIhg/ZsTChCfNz6xqLLa6X5n1H97DaV0sWhIYHIK5M01AtSdW7VZaVezl4i2lN7R+YczlYuKb6jGcpyDevcne4Ab40khA8DYe5/Lt9j0XcrKaQTXnuTDhG6BZCEyKk6aU39MorXhlopQRh9XmxbSUv2glfQe5Q=
  app: summit-register
  skip_cleanup: true
